name: CI - Build/compile check

on:
  push:
    branches: [ main, master, dev ]
  pull_request:
    branches: [ main, master, dev ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: prepare
      run: |
        cd extern
        git clone https://github.com/Microsoft/vcpkg.git
    - name: configure
      run: |
        cd build
        cmake -S .. -B . -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release
    - name: building
      run: |
        cd build
        cmake --build . --config Release