name: CI Tests

on:
  push:
    branches: [ main, master, dev ]
  pull_request:
    branches: [ main, master, dev ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: install
      run: |
        sudo apt-get install gcovr lcov
    - name: prepare
      run: |
        cd extern
        git clone https://github.com/Microsoft/vcpkg.git
    - name: configure
      run: |
        cmake -H. -Bbuild -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Debug -DENABLE_COVERAGE=On
    - name: building
      run: |
        cmake --build build --config Debug
    - name: testing
      run: |
        cd build
        ctest
        bash <(curl -s https://codecov.io/bash)